// GENERATED by scripts/audit-window-bridge.mjs --declare. Do not edit by hand.
//
// Milestone 42C: the classic-script <-> ES-module bridge, declared. Every
// name a module assigns to or reads from `window` is listed here so that
// `tsc --noEmit` can check those modules at all. Everything is `any` until
// someone tightens a specific name; tests/unit/window-bridge.spec.js fails
// when this file is out of date with the source.

interface Window {
  __GUARDIAN_FORMS_TEST_MODE__: any;
  GuardianForms: any;
}
